name: Build Fabric Mod

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build the mod
        run: ./gradlew build

      - name: Upload mod jar
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar
          path: build/libs/*.jar
